### PR TITLE
Code refactoring

### PR DESCRIPTION
**Pull request by Anton-Latukha**
Refactoring got out of hand very quickly to gradually commit it.

I'd maybe requested merge rights, but plan to change the project pretty drastically to negotiate all of the changes.

And I don't like splitting the community efforts and sources by forks when the transfer seems possible.

Maybe you would be interested to organize the transfer. I'd transformed and maintained it and published to Hackage and maintained further after.
If you wish, and as you deserve - with you as the author of the project.

Planning to take the source and change it so it does its main thing great and becomes very user friendly, to use it for practical use to migrate modules around in HNix.

### CODE REVIEW

**Comment by chrisdone** [comment]
I can just transfer the project over to you because I forgot it even existed!

**Comment by chrisdone** [comment]
You have to delete/rename your fork and then I can transfer the project to you.

**Comment by Anton-Latukha** [comment]
> You have to delete/rename your fork and then I can transfer the project to you.

Done.

> I can just transfer the project over to you because I forgot it even existed!

Thank you.

Seem to enjoy refactoring and maintaining projects. And maintaining the maintainer project seems like a great fit.

**Comment by chrisdone** [comment]
Done! Best of luck!

**Comment by Anton-Latukha** [comment]
Thank you, only best to you also.

**Comment by Anton-Latukha** [comment]
Seems strange.

I removed the fork before this.

Maybe it is due to the PR staying open.

**Comment by Anton-Latukha** [comment]
Ok.

If the transfer does not pan-out, then would go a git fork and continue with all this.
Processes in the project become quite complex, this tool after some development would help to do module infrastructure migrations. And I want to maintain it.

Thank you for everything.

**Comment by Anton-Latukha** [comment]
Email arrived.
Thank you.

**Pull request closed without merging**
